version: '3.7'
services:
  api:
    image: booston-url-shortener
    container_name: booston-url-shortener
    build: .
    restart: always
    command: npm run dev
    working_dir: /usr/src/app
    depends_on:
      - db
    volumes:
      - ./src:/usr/src/app/src
    ports:
      - 5000:80
    environment:
      - PG_DB=${PG_DB}
      - PG_HOST=${PG_HOST}
      - PG_PORT=${PG_PORT}
      - PG_USER=${PG_USER}
      - PG_PASS=${PG_PASS}
      - NODE_ENV=${NODE_ENV}

  db:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=${PG_DB}
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASS}

  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080
